"""Initial migration

Revision ID: 25c82965692c
Revises: 
Create Date: 2025-09-03 11:33:42.727752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '25c82965692c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('action', sa.Enum('CREATE', 'VIEW', 'EDIT', 'DELETE', 'SIGN', 'EXPORT', 'SHARE', 'APPROVE', 'REJECT', 'ARCHIVE', 'LOGIN', 'LOGOUT', name='auditaction'), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_name', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_role', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='auditrisklevel'), nullable=True))
    op.add_column('audit_logs', sa.Column('compliance_flag', sa.Boolean(), nullable=True))
    op.add_column('audit_logs', sa.Column('additional_metadata', sa.JSON(), nullable=True))
    op.drop_column('audit_logs', 'additional_data')
    op.drop_column('audit_logs', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('event_type', sa.VARCHAR(), nullable=False))
    op.add_column('audit_logs', sa.Column('additional_data', sqlite.JSON(), nullable=True))
    op.drop_column('audit_logs', 'additional_metadata')
    op.drop_column('audit_logs', 'compliance_flag')
    op.drop_column('audit_logs', 'risk_level')
    op.drop_column('audit_logs', 'location')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'user_role')
    op.drop_column('audit_logs', 'user_name')
    op.drop_column('audit_logs', 'resource_name')
    op.drop_column('audit_logs', 'action')
    # ### end Alembic commands ###
